<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AreaPartsSeeder extends Seeder
{
    public function run()
    {
        $areaParts = [
            ['id'=>1, 'name'=>'Glass Doors'],
            ['id'=>2, 'name'=>'Mayo table'],
            ['id'=>3, 'name'=>'OBGYNE Table'],
            ['id'=>4, 'name'=>'Foot stool'],
            ['id'=>5, 'name'=>'Glass Windows'],
            ['id'=>6, 'name'=>'Printers'],
            ['id'=>7, 'name'=>'Chairs'],
            ['id'=>8, 'name'=>'Doors'],
            ['id'=>9, 'name'=>'Office tables'],
            ['id'=>10, 'name'=>'Office chairs'],
            ['id'=>11, 'name'=>'Supply Cabinet'],
            ['id'=>12, 'name'=>'Wall Plugs'],
            ['id'=>13, 'name'=>'Light Switches'],
            ['id'=>14, 'name'=>'Fan Switches'],
            ['id'=>15, 'name'=>'Wall Faucet'],
            ['id'=>16, 'name'=>'Tables'],
            ['id'=>17, 'name'=>'Dust Bins'],
            ['id'=>18, 'name'=>'Computer Tables'],
            ['id'=>19, 'name'=>'Computer Unit'],
            ['id'=>20, 'name'=>'Filing Cabinets'],
            ['id'=>21, 'name'=>'Floor'],
            ['id'=>22, 'name'=>'Basin Unit'],
            ['id'=>23, 'name'=>'Fire Extinguishers'],
            ['id'=>24, 'name'=>'Copy/Printer Machine'],
            ['id'=>25, 'name'=>'Lockers'],
            ['id'=>26, 'name'=>'Drainpipes'],
            ['id'=>27, 'name'=>'Urinal'],
            ['id'=>28, 'name'=>'Toilet Units'],
            ['id'=>29, 'name'=>'Floor Drain'],
            ['id'=>30, 'name'=>'Paper towel dispenser'],
            ['id'=>31, 'name'=>'Handrail'],
            ['id'=>32, 'name'=>'Counter'],
            ['id'=>33, 'name'=>'Water Dispenser'],
            ['id'=>34, 'name'=>'Drawers'],
            ['id'=>35, 'name'=>'ER swing door'],
            ['id'=>36, 'name'=>'Pharmacy door'],
            ['id'=>37, 'name'=>'ER Bed'],
            ['id'=>38, 'name'=>'Wheelchairs'],
            ['id'=>39, 'name'=>'Buckets'],
            ['id'=>40, 'name'=>'Lab outside cubicle'],
            ['id'=>41, 'name'=>'Outside working table'],
            ['id'=>42, 'name'=>'Microwave'],
            ['id'=>43, 'name'=>'Countertop'],
            ['id'=>44, 'name'=>'ER glass door'],
            ['id'=>45, 'name'=>'Emergency cart'],
            ['id'=>46, 'name'=>'ECG Machine'],
            ['id'=>47, 'name'=>'Patient monitor'],
            ['id'=>48, 'name'=>'Defib machine'],
            ['id'=>49, 'name'=>'Wooden Table'],
            ['id'=>50, 'name'=>'IV stands'],
            ['id'=>51, 'name'=>'O2 tanks'],
            ['id'=>52, 'name'=>'Walls'],
            ['id'=>53, 'name'=>'Floor mat'],
            ['id'=>54, 'name'=>'Glass Panes'],
            ['id'=>55, 'name'=>'Security table'],
            ['id'=>56, 'name'=>'Security chair'],
            ['id'=>57, 'name'=>'Admitting table'],
            ['id'=>58, 'name'=>'Computer and Printer'],
            ['id'=>59, 'name'=>'Triage table'],
            ['id'=>60, 'name'=>'Triage chair'],
            ['id'=>61, 'name'=>'Lobby benches'],
            ['id'=>62, 'name'=>'White board'],
            ['id'=>63, 'name'=>'Benches'],
            ['id'=>64, 'name'=>'Lectern'],
            ['id'=>65, 'name'=>'Floor & Carpet'],
            ['id'=>66, 'name'=>'Mirror'],
            ['id'=>67, 'name'=>'Wooden Door'],
            ['id'=>68, 'name'=>'Bucket/Faucet'],
            ['id'=>69, 'name'=>'Computer Monitors'],
            ['id'=>70, 'name'=>'Counter Table'],
            ['id'=>71, 'name'=>'Floor & Floor drain'],
            ['id'=>72, 'name'=>'Glass table'],
            ['id'=>73, 'name'=>'Wooden office doors'],
            ['id'=>74, 'name'=>'Swing door'],
            ['id'=>75, 'name'=>'Door/Door frame'],
            ['id'=>76, 'name'=>'Washing Machine'],
            ['id'=>77, 'name'=>'Dryer'],
            ['id'=>78, 'name'=>'Washing Baskets'],
            ['id'=>79, 'name'=>'Clothes hamper'],
            ['id'=>80, 'name'=>'Linen Cabinet'],
            ['id'=>81, 'name'=>'Staff Locker'],
            ['id'=>82, 'name'=>'Wash bay area'],
            ['id'=>83, 'name'=>'Mop buckets'],
            ['id'=>84, 'name'=>'LED film viewer'],
            ['id'=>85, 'name'=>'X-ray Machine & table'],
            ['id'=>86, 'name'=>'Waste bin'],
            ['id'=>87, 'name'=>'Hand towel rail'],
            ['id'=>88, 'name'=>'Circuit breaker'],
            ['id'=>89, 'name'=>'Stainless steel rails'],
            ['id'=>90, 'name'=>'Tabletop'],
            ['id'=>91, 'name'=>'Fridge'],
            ['id'=>92, 'name'=>'Emergency cart'],
            ['id'=>93, 'name'=>'Working counter tops'],
            ['id'=>94, 'name'=>'Signage'],
            ['id'=>95, 'name'=>'Bucket & Tabo'],
            ['id'=>96, 'name'=>'Bump guards'],
            ['id'=>97, 'name'=>'Basin & faucet'],
            ['id'=>98, 'name'=>'Wall faucet'],
            ['id'=>99, 'name'=>'Wall mounted cabinet'],
            ['id'=>100, 'name'=>'Basin, faucet, drainpipe'],
            ['id'=>101, 'name'=>'Handwashing area'],
            ['id'=>102, 'name'=>'Steps'],
            ['id'=>103, 'name'=>'Basinet'],
            ['id'=>104, 'name'=>'Toilet door'],
            ['id'=>105, 'name'=>'Minor OR table'],
            ['id'=>106, 'name'=>'Stainless steel table'],
            ['id'=>107, 'name'=>'Stainless steel trolley table'],
            ['id'=>108, 'name'=>'Wooden mayo table'],
            ['id'=>109, 'name'=>'Small stainless steel table'],
            ['id'=>110, 'name'=>'Adjustable chair/stool'],
            ['id'=>111, 'name'=>'Minor OR wash bay'],
            ['id'=>112, 'name'=>'TV Set'],
            ['id'=>113, 'name'=>'Cabinets'],
            ['id'=>114, 'name'=>'Beds'],
            ['id'=>115, 'name'=>'Windows'],
            ['id'=>116, 'name'=>'CR walls'],
            ['id'=>117, 'name'=>'Emergency light'],
            ['id'=>118, 'name'=>'Wall clock'],
            ['id'=>119, 'name'=>'Wall frames'],
            ['id'=>120, 'name'=>'Bulletin board'],
            ['id'=>121, 'name'=>'Wi-Fi Unit'],
            ['id'=>122, 'name'=>'Fire alarm'],
            ['id'=>123, 'name'=>'Wall Mounted Shelves'],
            ['id'=>124, 'name'=>'Intercom'],
            ['id'=>125, 'name'=>'Aluminum Door'],
            ['id'=>126, 'name'=>'Power Supply Unit'],
            ['id'=>127, 'name'=>'Fire Hydrant'],
            ['id'=>128, 'name'=>'Wooden Cabinet'],
            ['id'=>129, 'name'=>'Film Cabinet'],
            ['id'=>130, 'name'=>'CCTV'],
            ['id'=>131, 'name'=>'Shelves'],
            ['id'=>132, 'name'=>'Stationary Cabinet'],
            ['id'=>133, 'name'=>'Book shelf'],
            ['id'=>134, 'name'=>'Shower unit'],
            ['id'=>135, 'name'=>'Built-in shelves'],
            ['id'=>136, 'name'=>'Couch'],
            ['id'=>137, 'name'=>'Wall Decors and Frames'],
            ['id'=>138, 'name'=>'Light Fittings'],
            ['id'=>139, 'name'=>'Directional signages'],
            ['id'=>140, 'name'=>'Book rack'],
            ['id'=>141, 'name'=>'Overhead lights'],
            ['id'=>142, 'name'=>'Bed & bed frame'],
            ['id'=>143, 'name'=>'Floor and wall corners'],
            ['id'=>144, 'name'=>'Fire hose reel box'],
            ['id'=>145, 'name'=>'Manual weighing scale'],
            ['id'=>146, 'name'=>'Signages & wall frames'],
            ['id'=>147, 'name'=>'Sprinkler system pipes'],
            ['id'=>148, 'name'=>'Curtain rail'],
            ['id'=>149, 'name'=>'Aircon drainage pipe'],
            ['id'=>150, 'name'=>'Portable light'],
            ['id'=>151, 'name'=>'Ceiling'],
            ['id'=>152, 'name'=>'Wi-Fi Repeater'],
            ['id'=>153, 'name'=>'X-ray Red Light'],
            ['id'=>154, 'name'=>'Exhaust fans'],
            ['id'=>155, 'name'=>'Ceiling fans'],
            ['id'=>156, 'name'=>'Sprinkler pipes'],
            ['id'=>157, 'name'=>'Wall speaker'],
            ['id'=>158, 'name'=>'Roller shutter door'],
            ['id'=>159, 'name'=>'Lights'],
            ['id'=>160, 'name'=>'Ceiling Light Fittings'],
            ['id'=>161, 'name'=>'Aircon'],
            ['id'=>162, 'name'=>'Fire Extinguisher pipes'],
            ['id'=>163, 'name'=>'Cubicle glass divider'],
        ];

        DB::table('area_parts')->insert($areaParts);
    }
}