<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    public function run()
    {
        $locations = [
            ['id'=>1, 'name'=>'Ultrasound Room', 'floor'=>'1st Floor'],
            ['id'=>2, 'name'=>'Ramp Area', 'floor'=>'1st Floor'],
            ['id'=>3, 'name'=>'X-ray Room', 'floor'=>'1st Floor'],
            ['id'=>4, 'name'=>'X-ray Room | Dressing Room', 'floor'=>'1st Floor'],
            ['id'=>5, 'name'=>'X-ray Room | CR', 'floor'=>'1st Floor'],
            ['id'=>6, 'name'=>'X-ray Room | Dark Room', 'floor'=>'1st Floor'],
            ['id'=>7, 'name'=>'Laundry', 'floor'=>'1st Floor'],
            ['id'=>8, 'name'=>'Hallway(Office Block to Ramp)', 'floor'=>'1st Floor'],
            ['id'=>9, 'name'=>'Janitorial Department', 'floor'=>'1st Floor'],
            ['id'=>10, 'name'=>'Suite Room', 'floor'=>'1st Floor'],
            ['id'=>11, 'name'=>'Suite Room | CR', 'floor'=>'1st Floor'],
            ['id'=>12, 'name'=>'MIS Office', 'floor'=>'1st Floor'],
            ['id'=>13, 'name'=>'HR Office', 'floor'=>'1st Floor'],
            ['id'=>14, 'name'=>'HR Office | CR', 'floor'=>'1st Floor'],
            ['id'=>15, 'name'=>"Administrator's office", 'floor'=>'1st Floor'],
            ['id'=>16, 'name'=>'Finance Department', 'floor'=>'1st Floor'],
            ['id'=>17, 'name'=>'Billing Department', 'floor'=>'1st Floor'],
            ['id'=>18, 'name'=>'Hallway (Cafeteria Area)', 'floor'=>'1st Floor'],
            ['id'=>19, 'name'=>'Hallway (Cafeteria Area) | CR', 'floor'=>'1st Floor'],
            ['id'=>20, 'name'=>'Prayer Room', 'floor'=>'1st Floor'],
            ['id'=>21, 'name'=>'Prayer Room | CR', 'floor'=>'1st Floor'],
            ['id'=>22, 'name'=>'Main Lobby (Reception Area)', 'floor'=>'1st Floor'],
            ['id'=>23, 'name'=>'Emergency Room', 'floor'=>'1st Floor'],
            ['id'=>24, 'name'=>'Emergency Room | CR', 'floor'=>'1st Floor'],
            ['id'=>25, 'name'=>"Doctor's Quarter", 'floor'=>'1st Floor'],
            ['id'=>26, 'name'=>"Doctor's Quarter | Doctor's Room", 'floor'=>'1st Floor'],
            ['id'=>27, 'name'=>"Doctor's Quarter | CR", 'floor'=>'1st Floor'],
            ['id'=>28, 'name'=>"Nurses Quarter", 'floor'=>'1st Floor'],
            ['id'=>29, 'name'=>"Lab & Radiology Waiting Area", 'floor'=>'1st Floor'],
            ['id'=>30, 'name'=>"Lab & Radiology Waiting Area | CR", 'floor'=>'1st Floor'],
            ['id'=>31, 'name'=>'Hallway (OPD to Triage Area)', 'floor'=>'1st Floor'],
            ['id'=>32, 'name'=>'Records', 'floor'=>'1st Floor'],
            ['id'=>33, 'name'=>'OPD Waiting Area', 'floor'=>'1st Floor'],
            ['id'=>34, 'name'=>'OPD Waiting Area | CR (Male)', 'floor'=>'1st Floor'],
            ['id'=>35, 'name'=>'OPD Waiting Area | CR (Female)', 'floor'=>'1st Floor'],
            ['id'=>36, 'name'=>'IW Room', 'floor'=>'1st Floor'],
            ['id'=>37, 'name'=>'OPD Waiting Area | CR (PWD)', 'floor'=>'1st Floor'],
            ['id'=>38, 'name'=>'Hallway (MED. & E-Konsulta)', 'floor'=>'1st Floor'],
            ['id'=>39, 'name'=>'Hallway (OB & Nursing Dept. Office)', 'floor'=>'1st Floor'],
            ['id'=>40, 'name'=>'OB GYNE Room', 'floor'=>'1st Floor'],
            ['id'=>41, 'name'=>'Nursing Director Office', 'floor'=>'1st Floor'],
            ['id'=>42, 'name'=>'OBGYNE Office', 'floor'=>'1st Floor'],
            ['id'=>43, 'name'=>'Room 205', 'floor'=>'2nd Floor'],
            ['id'=>44, 'name'=>'Room 205 | CR', 'floor'=>'2nd Floor'],
            ['id'=>45, 'name'=>'OB Ward', 'floor'=>'2nd Floor'],
            ['id'=>46, 'name'=>'OB Ward | CR', 'floor'=>'2nd Floor'],
            ['id'=>47, 'name'=>'Isolation Room', 'floor'=>'2nd Floor'],
            ['id'=>48, 'name'=>'Isolation Room | CR', 'floor'=>'2nd Floor'],
            ['id'=>49, 'name'=>'Stairs Area', 'floor'=>'2nd Floor'],
            ['id'=>50, 'name'=>'Room 203', 'floor'=>'2nd Floor'],
            ['id'=>51, 'name'=>'Room 203 | CR', 'floor'=>'2nd Floor'],
            ['id'=>52, 'name'=>'Room 202', 'floor'=>'2nd Floor'],
            ['id'=>53, 'name'=>'Room 202 | CR', 'floor'=>'2nd Floor'],
            ['id'=>54, 'name'=>'Room 204', 'floor'=>'2nd Floor'],
            ['id'=>55, 'name'=>'Room 204 | CR', 'floor'=>'2nd Floor'],
            ['id'=>56, 'name'=>'Room 201', 'floor'=>'2nd Floor'],
            ['id'=>57, 'name'=>'Room 201 | CR', 'floor'=>'2nd Floor'],
            ['id'=>58, 'name'=>'General Ward', 'floor'=>'2nd Floor'],
            ['id'=>59, 'name'=>'General Ward | CR', 'floor'=>'2nd Floor'],
            ['id'=>60, 'name'=>'Lobby Area & Stairs', 'floor'=>'2nd Floor'],
            ['id'=>61, 'name'=>'Nurse Station 1', 'floor'=>'2nd Floor'],
            ['id'=>62, 'name'=>'Nurse Station 1 | CR', 'floor'=>'2nd Floor'],
            ['id'=>63, 'name'=>'Central Supply Room', 'floor'=>'2nd Floor'],
            ['id'=>64, 'name'=>'Central Supply Room | CR', 'floor'=>'2nd Floor'],
            ['id'=>65, 'name'=>'Male Ward', 'floor'=>'2nd Floor'],
            ['id'=>66, 'name'=>'Male Ward | CR', 'floor'=>'2nd Floor'],
            ['id'=>67, 'name'=>'Female Ward', 'floor'=>'2nd Floor'],
            ['id'=>68, 'name'=>'Female Ward | CR', 'floor'=>'2nd Floor'],
            ['id'=>69, 'name'=>'Hallway (between male & female wards)', 'floor'=>'2nd Floor'],
            ['id'=>70, 'name'=>'Hallway (O.R. to ramp)', 'floor'=>'2nd Floor'],
            ['id'=>71, 'name'=>'Nurse Station 2', 'floor'=>'2nd Floor'],
            ['id'=>72, 'name'=>'Nurse Station 2 | CR', 'floor'=>'2nd Floor'],
            ['id'=>73, 'name'=>'Hallway/CR', 'floor'=>'2nd Floor'],
            ['id'=>74, 'name'=>'Hallway/CR | CR', 'floor'=>'2nd Floor'],
            ['id'=>75, 'name'=>'SMP 1 & 2', 'floor'=>'2nd Floor'],
            ['id'=>76, 'name'=>'SMP 1 & 2 | CR', 'floor'=>'2nd Floor'],
            ['id'=>77, 'name'=>'NICU', 'floor'=>'2nd Floor'],
            ['id'=>78, 'name'=>'NICU | CR', 'floor'=>'2nd Floor'],
            ['id'=>80, 'name'=>'Operating room | Minor OR', 'floor'=>'2nd Floor'],
            ['id'=>81, 'name'=>'Operating room | CR', 'floor'=>'2nd Floor'],
            ['id'=>82, 'name'=>'CR (LAB & RADIOLOGY AREA)', 'floor'=>'2nd Floor'],
        ];

        DB::table('locations')->insert($locations);
    }
}